### ISSUE TITLE
Basic File Management

### ISSUE THREAD

**Issue by borhara** [SHIV5T3R/File-Manager#1]
# Outcome
The outcome of these tasks is to lay the groundwork for the rest of our project. 

# Criteria

- [ ] Creation of files/folders
- [ ] Deletion of files/folders
- [ ] Moving files/folders
- [ ] Duplicating files/folders 
- [ ] Renaming files/folders

**Comment by maxovicsteiner** [comment]
This has to be split into two different tasks. One to handle the definition of files folders and paths, implementing methods for each one; and one to design and make the UI for it, so drag&drop functionality, keyboard shortcuts etc.

**Comment by borhara** [comment]
Quite true. 

If anyone intends to work on of these, note whether you're working on the UX aspect or actual functionality (or both!)

**Comment by maxovicsteiner** [comment]
I did, I named the issue Core of the project, and am working in the logic (functionality) part.

**Comment by swordensen** [comment]
I believe this is done with https://github.com/SHIV5T3R/Maestro/pull/19

**Comment by swordensen** [comment]
but might be worth keeping open in case people have questions on how to use the API

**Comment by borhara** [comment]
This has been sorted with #19.

If anyone has questions, bring it up in the discussion channel in the discord server.
