### ISSUE TITLE
Base User Interface

### ISSUE THREAD

**Issue by borhara** [SHIV5T3R/File-Manager#3]
# Outcome

The outcome for this task is to create the base of the application's UI.

The rest of the tasks will follow this design style so we can also discuss this as a team.

## Things To Consider

- A dashboard for the application
- How files and folders will be laid out
- Context menus for files and folders

**Comment by jaybuurdd** [comment]
I'll make a navbar and menu sidebar to kick off our FE UI

Edit: Now that we have our new layout going to add a dashboard tab and search bar based on @rasteli changes :)

**Comment by rasteli** [comment]
I'll make the display of files and folder and give the user the option to view them as a list or a grid

**Comment by borhara** [comment]
#24 has just been merged to add the base dashboard. 

I think we should focus on refining it, feel free to take that up, make sure to comment if you are :D

**Comment by lotosotol** [comment]
I can test if you guys want me to?!
